version: "3.3"

services:
  
  nginx:
    build:
      context: .
      dockerfile: docker/nginx.Dockerfile
    restart: always
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./log/nginx/:/var/log/nginx/
    links:
      - fpm

  fpm:
    build:
      context: .
      dockerfile: docker/fpm.Dockerfile
    volumes:
      - ./:/var/www
    links:
      - db

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123321
      MYSQL_DATABASE: laravel

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080